name: Build, Test and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.get_image_name.outputs.image_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up Gradle
        run: ./gradlew clean

      - name: Build jar
        run: ./gradlew build

      - name: Get image name
        id: get_image_name
        run: |
          IMAGE_NAME=$(./gradlew -q dockerPrintImageName)
          echo "::set-output name=image_name::$IMAGE_NAME"
          echo "Image name is: $IMAGE_NAME"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up Gradle
        run: ./gradlew clean

      - name: Run unit tests
        run: ./gradlew test

  push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build docker image
        run: docker build -t "${{ vars.DOCKER_USERNAME }}/${{ needs.build.outputs.image_name }}" .

      - name: Push Docker image
        run: docker push "${{ vars.DOCKER_USERNAME }}/${{ needs.build.outputs.image_name }}"